version: 2.1

executors:
  windows:
    machine:
      image: windows-server-2019

jobs:
  build:
    executor: windows

    steps:
      - checkout

      - run:
          name: Install Python
          command: choco install python --version=3.11

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install nuitka

      - run:
          name: Set environment variables for Nuitka
          command: |
            setx NUITKA_ONEFILE_TEMP true
            setx NUITKA_RECURSIVE true

      - run:
          name: Build with Nuitka
          command: |
            nuitka --standalone --onefile --assume-yes-for-downloads --output-filename=ZZZ-UID.exe .\main.py

      - run:
          name: Rename executable
          command: |
            ren ZZZ-UID.dist\main.exe ZZZ-UID.exe

      - run:
          name: Archive executable and images
          command: |
            powershell Compress-Archive -Path .\ZZZ-UID.exe, .\img -DestinationPath ZZZ-UID.zip

      - store_artifacts:
          path: ZZZ-UID.zip
          destination: release

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
