name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka


      - name: Set environment variable for Nuitka
        run: |
          $env:NUITKA_ONEFILE_TEMP=true
          $env:NUITKA_RECURSIVE=true

      - name: Build with Nuitka
        run: |
          nuitka --standalone --onefile --assume-yes-for-downloads --output-filename=ZZZ-UID.exe --windows-uac-admin .\main.py


      - name: Archive executable and images
        run: |
          Compress-Archive -Path .\ZZZ-UID.exe, .\img -DestinationPath ZZZ-UID.zip

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_number }} - ${{ github.run_id }}
          draft: false
          prerelease: true

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ZZZ-UID.zip
          asset_name: ZZZ-UID.zip
          asset_content_type: application/zip
